### ISSUE TITLE
Game crashes sometimes when spawning landmines

### ISSUE THREAD

**Issue by Bryan-CoderS** [Darr3n2GG/The-Convoy#16]
**Describe the bug**
The game sudden crash when landmine position repeats (I guess?) I need someone who understand the code more to help to debug it.

**To Reproduce**
1. Go to 'landmine blinking section'
2. Code:
    if show_landmines:
        for landmine_pos in landmines: #??? unknown code
            pygame.draw.rect(game_window, RED, pygame.Rect(landmine_pos[0], landmine_pos[1], 10, 10))   
3. 
Exception has occurred: TypeError
'NoneType' object is not subscriptable
//system was referring to landmine_pos[0]//
TypeError: 'NoneType' object is not subscriptable

**Expected behavior**
I expect the game to run without sudden crash.

**Screenshots**
![Screenshot (7)](https://github.com/user-attachments/assets/4ca91084-075e-46a5-940d-05a80e9d1c40)

**Comment by Darr3n2GG** [comment]
Landmine spawning logic is inserting NoneType into list of landmines for some reason.

**Comment by Darr3n2GG** [comment]
Probably fixed. I have closed this as we have no time to ensure that this bug is actually fixed
