### ISSUE TITLE
List of things to do

### ISSUE THREAD

**Issue by Darr3n2GG** [Darr3n2GG/The-Convoy#4]
### What we need for the game:
-U-Boat (done)
-OPTIMISATIONS
-SFX (done)
-MAKE THE GAME LOOK COOLER
-SETTINGS
-ALL THE THINGS REQUIRED FOR THE PROJECT, REFER HERE :
  https://github.com/PenangScienceCluster/PythonCFA/wiki/Suggested-Scoring-Rubric-for-the-Projects

### Extra stuff:
-ENEMY
-HEALTH
-VFX

**Comment by Bryan-CoderS** [comment]
Is background music required?

Sound effects added:
sonar
reached checkpoint
hit by U-Boat

Sound effect not in used:
Alert

**Comment by cyberredcoat** [comment]
all done
